### ISSUE TITLE
Stacks.co update 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/stacks-brand#1]
(Originally posted by Jeff) -- Trying to solve two problems:

- Clarity for who is confused about what is what in ecosystem
- Singular URL to send or include as good entry point

Proposal:

- Stop redirecting Stacks.co to Stackstoken.com
- Create a simple page that inventories all the entities and provides clear guidance on what they do and any current weirdness. For example, we can show Hiro and explain that we are currently in the process of porting Blockstack PBC to Hiro.
- We prioritize this now and publish ASAP.

**Comment by GinaAbrams** [comment]
Here's the copy I'm thinking, pulled from blog posts: 
**Stacks Ecosystem:** Stacks brings apps and smart contracts to Bitcoin. The Stacks ecosystem is a collection of independent entities, developers, and community members working to build a user-owned internet on Bitcoin.

Lower and smaller text for the following: 
**Stacks Foundation:** The Stacks Foundation supports the mission of a user owned internet through Stacks-related governance, research and development, education, and grants.
**Hiro:** provides developers the tools they need to build the new internet on Bitcoin powered by apps and smart contracts on Stacks 2.0.
**Freehold** empowers communities to collaborate on open protocols, starting with Stacks.
**Daemon Technologies** builds technology and services to support individuals and entities intending to work with the Stacks 2.0 blockchain, driving adoption of Stacks-based technology in Asia. 

@cuevasm I assume we'll want to update copy but thoughts on this to get the ball rolling? @jasperjansz would you be able to help set up a basic site once copy is confirmed? cc @jeffdomke for any other notes.

**Comment by cuevasm** [comment]
These look like good starting places to me and then we can edit more once we see it in context 🙏
